const buffer = Buffer.from("Hello");
console.log("Original Buffer:", buffer);
console.log("String:", buffer.toString());
console.log("Buffer Length:", buffer.length);
console.log("First byte:", buffer[0]);
console.log("Second byte:", buffer[1]);
buffer[0] = 74; 
console.log("After modification:", buffer.toString());
const buffer2 = Buffer.alloc(5);
console.log("Allocated Buffer:", buffer2);
buffer2.write("Hello");
console.log("After writing:", buffer2.toString());
const b1 = Buffer.from("Hello ");
const b2 = Buffer.from("World");
const combined = Buffer.concat([b1, b2]);
console.log("Concatenated:", combined.toString());
const sliced = combined.slice(0, 5);
console.log("Sliced Buffer:", sliced.toString());
const sub = combined.subarray(6, 11);
console.log("Subarray:", sub.toString());
const text = "Hello World";
console.log("Byte Length:", Buffer.byteLength(text));
const x = Buffer.from("ABC");
const y = Buffer.from("ABC");
console.log("Buffer Compare:", Buffer.compare(x, y));